/* eslint-disable */
export enum talents {
  PRODUCER = "PRODUCER",
  SINGER = "SINGER",
  SONG_WRITER = "SONG WRITER",
  MUSIC_COMPOSER = "MUSIC COMPOSER",
  DIRECTOR = "DIRECTOR",
}

export enum languages {
  ENGLISH = "ENGLISH",
  SINHALA = "SINHALA",
  CHINESE = "CHINESE",
  JAPANESE = "JAPANESE",
  HINDI = "HINDI",
}

export enum country {
  SRI_LANKA = "SRI LANKA",
  INDIA = "INDIA",
  CHINA = "CHINESE",
  JAPAN = "JAPANESE",
  UNITED_KINGDOM = "UNITED KINGDOM",
  UNITED_STATE = "UNITED STATE",
  AUSTRALIA = "AUSTRALIA",
  SWITZERLAND = "SWITZERLAND",
}
